import { createTool } from '@mastra/core';
import { z } from 'zod';

export const codeGeneratorTool = createTool({
  id: 'code-generator-tool',
  description: 'Generate React/Next.js code based on user requirements with proper TypeScript typing, Tailwind CSS styling, and Next.js App Router compatibility',
  inputSchema: z.object({
    prompt: z.string().describe('The user requirements for generating the component'),
    componentName: z.string().optional().describe('Optional component name'),
  }),
  outputSchema: z.object({
    componentName: z.string(),
    description: z.string(),
    code: z.string(),
    dependencies: z.array(z.string()).optional(),
  }),
  execute: async ({ context }) => {
    const { prompt, componentName } = context;

    // This will be executed by the agent with Anthropic
    // The actual code generation happens through the LLM
    return {
      componentName: componentName || 'GeneratedComponent',
      description: `Component generated from: ${prompt}`,
      code: `// Component will be generated by the LLM based on the prompt`,
      dependencies: [],
    };
  },
});
